sudo: true
language: node_js
env:
  global:
  - CF_API=https://api.ng.bluemix.net/
  - CF_USERNAME=jamesrauhut@us.ibm.com
  - CF_ORG=jamesrauhut@us.ibm.com
  - CF_SPACE=dev
before_deploy:
  - wget https://s3.amazonaws.com/go-cli/releases/v6.12.4/cf-cli_amd64.deb -qO temp.deb && sudo dpkg -i temp.deb
  - rm temp.deb
  - cf login -a ${CF_API} -u ${CF_USERNAME} -p ${BLUEMIX_PASSWORD} -o ${CF_ORG} -s ${CF_SPACE}
  - cf install-plugin autopilot -r CF-Community
deploy:
- edge: true
  provider: script
  script: cf zero-downtime-push psuedo-fullstack -f ./manifest.yml
  on:
    branch: master
deploy:
- edge: true
  provider: script
  script: cf zero-downtime-push psuedo-fullstack-staging -f ./manifest-staging.yml
  on:
    branch: staging
notifications:
  slack:
    secure: passwordpasswordpasswordpasswordpassword